stages:
  - test
  
test:
  stage: test
  image: golang:1.11.5-alpine3.8
  before_script:
    - echo ${PACKAGE_PATH}
    - echo ${CI_PROJECT_DIR}
    - go get gitlab.com/jonas.jasas/condchan
  script:
    - go test gitlab.com/jonas.jasas/condchan