stages:
  - test
  
# A hack to make Golang-in-Gitlab happy
.anchors:
  - &inject-gopath
      mkdir -p $(dirname ${PACKAGE_PATH})
      && ln -s ${CI_PROJECT_DIR} ${PACKAGE_PATH}
      && cd ${PACKAGE_PATH}  
  
test:
    stage: test
    image: golang:1.10-alpine3.7
    before_script:
        - *inject-gopath
    script:
        - go test ./...