stages:
  - test

variables:
  GIT_STRATEGY: none

test:
  stage: test
  image: golang
  before_script:
    - go get gitlab.com/jonas.jasas/condchan
  script:
    - go test gitlab.com/jonas.jasas/condchan
    - echo $GOPATH
    - echo $GOROOT
    - cd $GOPATH/src/gitlab.com/jonas.jasas/condchan/examples; go build --race ./...