image: golang

variables:
  GIT_STRATEGY: none
  REPO_NAME: gitlab.com/jonas.jasas/condchan

stages:
  - build
  - test

before_script:
  - go get $REPO_NAME

build:
  stage: build
  script:
    - cd $GOPATH/src/$REPO_NAME
    - go build --race ./...

test:
  stage: test
  script:
    - go test $REPO_NAME -cover